=== blombo/zmw/applications/book/book-preferences.dtd
<!ELEMENT book-preferences (column*, column-order, color*)>

<!ELEMENT column EMPTY>

<!ELEMENT color EMPTY>

<!ELEMENT language EMPTY>

<!ELEMENT column-order (column-name*)>

<!ELEMENT column-name (#PCDATA)>

<!ATTLIST column
 name CDATA #REQUIRED
 width CDATA #IMPLIED
 visible CDATA #IMPLIED
 default CDATA #IMPLIED
>

<!ATTLIST color
 name CDATA #REQUIRED
 r CDATA #REQUIRED
 g CDATA #REQUIRED
 b CDATA #REQUIRED
>

<!ATTLIST language
 name CDATA #REQUIRED
>

=== blombo/zmw/applications/book/book-preferences.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE book-preferences SYSTEM "book-preferences.dtd">
<?xml-stylesheet type="text/xsl" href="book-preferences.xsl"?>
<book-preferences>
<column name='Title' width='400' visible='1' default='' />
<column name='Author' width='200' visible='1' default='?' />
<column name='Borrower' width='200' visible='1' />
<column name='Collection' width='200' visible='1' default='?' />
<column name='Number' width='50' visible='1' default='0' />
<column name='Rate' width='30' visible='1' default='9' />
<column-order>
	<column-name>Title</column-name>
	<column-name>Author</column-name>
	<column-name>Borrower</column-name>
	<column-name>Collection</column-name>
	<column-name>Rate</column-name>
	<column-name>Number</column-name>
</column-order>
<color name='standard' r='0.75' g='0.75' b='0.75' />
<color name='tip' r='0.75' g='0.75' b='0' />
<color name='header' r='0' g='0.75' b='0' />
<color name='borrowed' r='0.75' g='0.5' b='0.75' />
<color name='menu' r='0.9' g='0.9' b='0.9' />
<language name='french' />
</book-preferences>
